### ISSUE TITLE
catch situations where `PKGMAN_Exec` returns `fail`

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/PackageManager#123]
`InstallPackageFromGit( url )` calls `PKGMAN_Exec`, and expects that the result is a record.
Thus GAP runs into an error if `PKGMAN_Exec` returns `fail`.

**Comment by mtorpey** [comment]
Thanks for this!  I guess this will be an easy fix.

**Comment by mtorpey** [comment]
Actually when looking into this, I'm having trouble reproducing the issue.  Do you know of a common time when PKGMAN_Exec returns fail?

**Comment by fingolfin** [comment]
Does it handle case were `git` is not present on the user's machine? What happens if `git` is given an invalid URL (i.e. serves a 404; or serves an "access denied") ?

**Comment by ThomasBreuer** [comment]
The problem was indeed with `git`, but it was more subtle.
It disappears if one uses `PathSystemProgram` instead of `Filename` and `DirectoriesSystemPrograms`, see issue gap-system/gap/issues/5752 and the solution gap-system/gap/pull/5754.

**Comment by fingolfin** [comment]
So what shall we do then? Change `PKGMAN_Exec` to use `PathSystemProgram` if available (and otherwise fall back to existing code) ? Or should it also be changed to return a boolean? Or what?

**Comment by ThomasBreuer** [comment]
Actually the problem was fixed with #126, thus the issue can be closed.

As soon as `PathSystemProgram` becomes available in GAP, the code duplication can be removed, but that is another topic.
