### ISSUE TITLE
How to extract data from json?

### ISSUE THREAD

**Issue by mtorpey** [gap-packages/PackageManager#135]
We should start downloading package information from https://github.com/gap-system/PackageDistro/releases/download/latest/package-infos.json.gz and using the data there (which is more stable and vetted than just getting latest versions).

I've added `PKGMAN_GetPackageDistroJson` which downloads the file, but I'm not sure what to do with the JSON string once I've got it.  Here are the options:

1.  Use the json package.  This means introducing a dependency, which isn't ideal.
2.  Take code from the json package, and put it straight into PackageManager.  Requires compiling, which isn't great.
3.  Write a rudimentary json interpreter from scratch.  How hard could it be?
4.  Do some desperate hacky stuff where I just try to pull out the right information without really parsing the json, and hope for the best.
5.  Introduce a new format in https://github.com/gap-system/PackageDistro/ which PackageManager could read more easily.
6.  Something else?

Does anyone have any advice?

**Comment by mtorpey** [comment]
I did option 3.  It seems to work!

**Comment by fingolfin** [comment]
But `PKGMAN_GetPackageDistroJson` does not yet use it, does it?

Though of course `PKGMAN_GetPackageDistroJson` itself is not yet used anyway :-)

**Comment by mtorpey** [comment]
That's right – these are all in development, and not used actively yet.  They'll be part of a broader rewrite, since having all that data available up front will mean we can resolve dependencies in a much nicer way.

This is all leading to a 2.0 release, since quite a few bits of behaviour will be changed.  I'm doing all the development in `master`, and I've made a `stable-v1` branch for any further 1.* releases.  I should probably have documented this somewhere!
