### ISSUE TITLE
Move this package to gap-packages org?

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/PackageManager#23]
Is there a reason this is not in the `gap-packages`? There it would be more visible, and also e.g. listed on http://gap-packages.github.io (but perhaps that's precisely the reason not to have it there?)

**Comment by mtorpey** [comment]
I'd be quite happy to move this to `gap-packages`, if you think that's the right place for it.  My main concern is that I wouldn't want, by moving the package, to suggest anything about the completeness or brilliance of the package.  But I like visibility, and as we can see from the issues James has posted, things can be improved by more people using them.

In short, if you think `gap-packages` is the place for this, please go ahead and make a repository and I'll push the project to it.  But if you think it'd be worth waiting till we have more features, I'd be fine with that too.

**Comment by fingolfin** [comment]
I really have no strong opinion on this, as I already know where the package is ;-). That said, I don't see anything bad about making it *slightly* more visible that way -- only "power users" will discover it by looking at the `gap-packages` org anyway, regular users won't find it there either. Maybe run a quick poll by people like @ChrisJefferson @james-d-mitchell  @alex-konovalov @markuspf @wilfwilson ... ?

**Comment by wilfwilson** [comment]
May as well move it to `gap-packages`.

**Comment by mtorpey** [comment]
Markus and James are both in favour too.  Having considered it, it sounds like a good idea to me!

**Comment by mtorpey** [comment]
As can be seen, this is done!
