### ISSUE TITLE
Make documentation if necessary

### ISSUE THREAD

**Issue by mtorpey** [gap-packages/PackageManager#28]
In particular, this is necessary if we download from Git or Hg.  Right now we aren't even calling `PKGMAN_CheckPackage` on these, because it would always return false.

**Comment by fingolfin** [comment]
Perhaps we could extract some of the relevant code from the release tools and share it. At the very least, it might serve as inspiration.

**Comment by mtorpey** [comment]
This is done as of current `master`.  Will be released in the coming days after there are slightly better tests.

**Comment by mtorpey** [comment]
This is tested fully, and released in `v0.5`.  The code from ReleaseTools was very helpful.
