### ISSUE TITLE
Explain where packages are installed

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/PackageManager#31]
It will be useful to explain in the manual that the packages are installed in `.gap/pkg` (on Windows - `_gap/pkg`) directory.

First, macOS users having their GAP customisations in `/Users/username/Library/Preferences/GAP` have to migrate them to `.gap`.

Second, advise that starting GAP with `-r` will not use any of the packages installed in `.gap/pkg`. This may be advised if one wants to compare the behaviour with standard GAP installation. Also, this is the way how GAP is started with `make test{install/standard/etc/}`.

**Comment by mtorpey** [comment]
Done in 269b1c0.
