### ISSUE TITLE
Status of standard tests

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/PackageManager#40]
Tests pass on Kovacs in Jenkins, but fail on Travis: https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/jobs/497572967 - hope that's not critical, but something to investigate.

**Comment by mtorpey** [comment]
I've just managed to reproduce this locally!

I believe the problem is that Mercurial is not installed on this Travis environment, and so the `hg` shell command is not being recognised.

Is there a way that `hg` could be made available before running the test?

**Comment by alex-konovalov** [comment]
Yes - I have added it here:
- https://github.com/gap-system/gap-docker-master/commit/62f0a44d7185d471d8808309fca5948df95deafc
- https://github.com/gap-system/gap-docker-stable-4.10/commit/e44acaaebd235ce0e9c389694d22dc2756e362fa

Let's check in a couple of days if this will help.

**Comment by mtorpey** [comment]
This is fixed, and shows up as passing in the `-staging` tests!
