### ISSUE TITLE
Rebuild packages if they are installed but can't be loaded

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/PackageManager#41]
This is more of a suggestion than an issue. It'd be useful if `InstallPackage("io");` checked if `io` was actually loadable, and not only installed. For example, when I switch from using the `stable-4.10` branch of GAP to using the `master` branch, I have to recompile all the packages, but there is no way of doing this currently with the `PackageMan`, other than:

~~~~
PKGMAN_CompileDir(UserHomeExpand("~/.gap/pkg/io-4.5.4"));
~~~~

**Comment by mtorpey** [comment]
Sounds like a good idea.  But how easy is it to tell whether a package is loadable?  Can it be done without actually attempting to load the package?

**Comment by james-d-mitchell** [comment]
Can't you use `TestPackageAvailability("digraphs");` for example?

**Comment by mtorpey** [comment]
Oh, so you can!  I didn't think `TestPackageAvailability` would actually pick up the case you're talking about, i.e. a package needing to be recompiled after GAP changes.  I thought most of the packages just checked whether a `.so` file exists and left it at that.  But I've tried updating to stable-4.10 and `TestPackageAvailability("io")` does actually return fail.

So yes, we should check this in the package manager, and recompile if necessary, presumably during `InstallPackage` and `UpdatePackage`.

Thanks!

**Comment by james-d-mitchell** [comment]
Great thanks @mtorpey

**Comment by mtorpey** [comment]
I think this is now done.  I don't know if it'll work every time, since your `io` use-case is tricky to include in tests, but I updated GAP to `stable-4.10` and managed to get this:

```
 ┌───────┐   GAP 4.10.1-1-g9d9e615 of today
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv3
 Configuration:  gmp 6.1.2, readline
 Loading the library and packages ...
 Packages:   GAPDoc 1.6.2, PackageManager 0.3, PrimGrp 3.3.2, SmallGrp 1.3, 
             TransGrp 2.0.4
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> TestPackageAvailability("io");
fail
gap> LoadPackage("io");
#I  IO package is not available. To see further details, enter
#I  SetInfoLevel(InfoPackageLoading,4); and try to load the package again.
fail
gap> InstallPackage("io");
#I  Getting PackageInfo URLs...
#I  Retrieving PackageInfo.g from https://gap-packages.github.io/io/PackageInfo.g ...
#I  PackageInfo.g validated successfully
#I  The newest version of package "io" is already installed
#I  Running compilation script on /home/mtorpey/.gap/pkg/io-4.6.0 ...
#I  Compilation was successful
true
gap> LoadPackage("io");
──────────────────────────────────────────────────────────────────────────────────
Loading  IO 4.6.0 (Bindings for low level C library I/O routines)
by Max Neunhöffer (http://www-groups.mcs.st-and.ac.uk/~neunhoef).
Homepage: https://gap-packages.github.io/io
──────────────────────────────────────────────────────────────────────────────────
true
```
Is that the kind of thing you were hoping for?

**Comment by james-d-mitchell** [comment]
Yeah, that's great @mtorpey! I tried it and it seems to work well.
