### ISSUE TITLE
Do not use QaoS package for tests

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/PackageManager#43]
It is being withdrawn, see https://github.com/gap-system/gap-distribution/commit/337de02e70a2f49ecfa76a9f6208d0294bff189a. 

As a result, this test failed:
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/510473986

**Comment by mtorpey** [comment]
The tests now contain no references to qaos.

After I make a release (probably today) I'll keep an eye on the tests linked above.

**Comment by mtorpey** [comment]
I believe this is fixed, based on the `-staging` version of the tests.
