### ISSUE TITLE
Improve the documentation about updating packages

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/PackageManager#44]
At present there's no section in the manual about how to update packages. The only thing I found was the sentence:

> Certain decisions, such as installing newer versions of packages, will be confirmed by the user via an interactive shell - to avoid this interactivity and use sane defaults instead, the optional second argument interactive can be set to false.

in the man section of `InstallPackage`. It might be more helpful to have a section in the manual entitled "Updating packages" with details of what to do, and what the sane defaults are.

**Comment by mtorpey** [comment]
This is actually on its way - I'm in the middle of redesigning how updating and installing works, including adding an explicit function called `UpdatePackage` (see #33).  It'll be added soon, along with much better documentation.

**Comment by james-d-mitchell** [comment]
Aha, great! I look forward to the update.

**Comment by mtorpey** [comment]
This is done, and the doc for `UpdatePackage` is near the top.  Hopefully a release soon, once I've tested everything properly.

Please open more issues if you happen to try it and anything doesn't seem right!
