### ISSUE TITLE
Tests fail again

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/PackageManager#48]
See e.g. https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/564286296 and https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10/jobs/564389217

**Comment by mtorpey** [comment]
Thanks for the report!  This looks like it may be caused by changes in GAPDoc-1.6.3, but I'll find out when I investigate today.

**Comment by mtorpey** [comment]
I'm actually having trouble reproducing this.

@alex-konovalov: is AutoDoc installed during the running of those tests?  And if so, what version?

**Comment by alex-konovalov** [comment]
Yes, as you can see in GAP banners - AutoDoc 2019.07.17

**Comment by mtorpey** [comment]
Ah yes!  I was only looking at the `-A` test.

Interesting.  I'll keep trying to reproduce...

**Comment by mtorpey** [comment]
Tests are still failing here:
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11-staging/jobs/586442586

Should sort this soon...

**Comment by nagygp** [comment]
It seems to me that the `enumitem.sty` file is needed. The latex package `enumitem` is required by AutoDoc and/or GAPDoc to compile manual.tex. 

In Ubuntu 18.04, the deb package `texlive-latex-extra` contains this file. However, it is not part of the standard ubuntu+gap docker container.

**Comment by mtorpey** [comment]
I've been looking at this again today, and I think @nagygp could well be right.

@alex-konovalov, is there any way to add `texlive-latex-extra` to the failing builds, perhaps by installing it in `gap-docker-base`?

**Comment by alex-konovalov** [comment]
@mtorpey we don't actually want to add latex there, as it will substantially increase the container size (https://github.com/gap-system/gap-docker/issues/11). That's why we used to get manuals archive in gap-container (thanks for making me look at this, discovered now https://github.com/gap-system/gap-docker/issues/23).

**Comment by mtorpey** [comment]
Thanks for looking into this.  I can see that adding texlive to the docker container would be a big overhead.

@alex-konovalov: Is there any other way to get access to texlive in the docker tests?  It's definitely a requirement for these tests to pass, since PackageManager is designed to build package documentation, and needs LaTeX to do this.

**Comment by mtorpey** [comment]
I fixed this in much the same way I did for Memoisation, by creating an alternative, limited test suite and installing that as the default tests in PackageInfo.g

The limited suite runs everything that doesn't require texlive, while `testall.g` and Travis still run the full suite.

See it passing here:
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master-devel/jobs/645549749

**Comment by mtorpey** [comment]
Also passing for stable GAP:
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.11-devel/jobs/645550214
https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10-devel/jobs/645105591

Thanks @alex-konovalov for helping me understand this and fix it!

**Comment by mtorpey** [comment]
Time for a release!
