### ISSUE TITLE
Allow installing latest version of a package *in the package distribution

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/PackageManager#54]
The latest version of a package in the package distribution might be older than the latest version of the package; but it has the advantage of being "blessed" by the GAP team in the sense that we performed some extensive testing with it present.

Perhaps PackageManager could have an option to allow restricting to such a version. Slightly related to issue #53 in that the feature there would help with the feature requested here.

**Comment by fingolfin** [comment]
Oh, and of course one could refine this further and wonder what happens if the GAP being run is outdated: If I run GAP 4.11 yet 4.12 is out, then some packages in the distribution might actually require GAP 4.12, so I shouldn't be updated to those... I guess that means we need different package distributions for each major GAP version. But actually we kinda have that. What is not clear to me is whether we have a nicely accessible list (e.g. as a JSON file) of these versions somewhere ... @alex-konovalov

**Comment by alex-konovalov** [comment]
Either we already have a nice JSON list after GapWWW switch to Jekyll, or, if not, should add it to the new website content generating code.

**Comment by mtorpey** [comment]
This is captured well by #84, which should be a priority.
