### ISSUE TITLE
Fail to load PackageManager

### ISSUE THREAD

**Issue by jcguu95** [gap-packages/PackageManager#56]
I'm on GAP 4.11.0 with `GAPDoc-1.6.3`. I downloaded the repo here, unpack, and put `PackageManager-master` directly into`/usr/lib/gap/pkg`. And I tried to load it... with the following error:

```
┌───────┐   GAP 4.11.0 of 29-Feb-2020
 │  GAP  │   https://www.gap-system.org
 └───────┘   Architecture: x86_64-pc-linux-gnu-default64-kv7
 Configuration:  gmp 6.2.0, GASMAN, readline
 Loading the library and packages ...
 Packages:   Alnuth 3.1.2, AtlasRep 2.1.0, AutPGrp 1.10.2, CRISP 1.4.5,
             CTblLib 1.2.2, FactInt 1.6.3, FGA 1.4.0, GAPDoc 1.6.3,
             IRREDSOL 1.4, LAGUNA 3.9.3, Polycyclic 2.15.1, PrimGrp 3.4.0,
             SmallGrp 1.4.1, Sophus 1.24, TomLib 1.2.9, TransGrp 2.0.5
 Try '??help' for help. See also '?copyright', '?cite' and '?authors'
gap> LoadPackage("PackageManager");
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `Filename' on 2 arguments
The 1st argument is 'fail' which might point to an earlier problem
 at /usr/lib/gap/lib/methsel2.g:249 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at /usr/lib/gap/pkg/PackageManager-master/gap/PackageManager.gd:239
type 'quit;' to quit to outer loop
brk>
```

And then I pressed `Ctrl-D` to escape, and load it again
```
gap> LoadPackage("PackageManager");
true
```

It seems to work without complaints. But the main function fails to work

```
gap> InstallPackage("xmod");
Error, InstallPackage: function is not yet defined
not in any function at *stdin*:2

gap> InstallPackage;
function( args... ) ... end

```

It seems that GAP knows that `InstallPackage` is a function, but doesn't know its definition.

**Comment by alex-konovalov** [comment]
How did you install GAP? If you have installed GAP 4.11.0 from https://www.gap-system.org/Releases/4.11.0.html, then PackageManager package would be already included in the GAP installation.

It was not loaded properly - after `Ctrl-D` the state of the package loading was corrupted, so even it's reported as loaded, only part of it is there (so it read the declaration of `InstallPackage` but not its actual code).

To investigate, you need to look at details in the break loop 
```
gap> LoadPackage("PackageManager");
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `Filename' on 2 arguments
The 1st argument is 'fail' which might point to an earlier problem
 at /usr/lib/gap/lib/methsel2.g:249 called from
<function "HANDLE_METHOD_NOT_FOUND">( <arguments> )
 called from read-eval loop at /usr/lib/gap/pkg/PackageManager-master/gap/PackageManager.gd:239
type 'quit;' to quit to outer loop
brk>
```
Could you please show the output of these commands:
```
ShowArguments( );
ShowDetails();
```
(what they do is described at https://www.gap-system.org/Manuals/doc/ref/chap7.html).

**Comment by jcguu95** [comment]
Thank you so much for your hint! I used archlinux's package manager to install `gap`. They might hack around things that I'm not aware of. However, after getting a supplementary `gap-packages`, which includes `PackageManager` from the arch package manager system, it did load `GAP:PackageManager` successfully. 

That said, I still get problem while installing packages using `GAP:PackageManager`.. this time the complaint is `... is not root directory. There's no sysinfo.gap`. I guess the best way is to compile `GAP` by myself from scratch..

**Comment by alex-konovalov** [comment]
Thanks for details. I don't know enough about this alternative distribution, but if they change things (like e.g. splitting it into several components), then it's plausible that something stops working. I'd advise to compile from scratch GAP and packages, as the GAP website says. 

Having said that,

> I still get problem while installing packages using GAP:PackageManager.. this time the complaint is ... is not root directory. There's no sysinfo.gap. 

perhaps @mtorpey will be able to advise. I think it will be very helpful if GAP:PackageManager would work in an alternative distribution, as a means to add missing packages or newer versions of installed packages to it.
