### ISSUE TITLE
Remove the dependence on GAPdoc

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/PackageManager#63]
I don’t know if this is technically feasible, but it’d be most useful if the package manager didn’t depend on any other packages at all (in the sense that there are no needed packages). It’d be useful to be able to start GAP with no packages other than the package manager and use it to install all further packages. At present this isn’t possible because GAPdoc is required.

**Comment by alex-konovalov** [comment]
It's an interesting question. Many packages use GAPDoc directly or via AutoDoc to build their manuals, and you can find all variations:
- required
- suggested
- not depending at all.

Once we thought that as a guideline, **required** is only applicable if some GAPDoc functions are used at package runtime (e.g. to parse OpenMath XML in the OpenMath package). Building manuals in this case is not required. Could certainly be made suggested (it will be used when one will use the help system to access package manual from the GAP session) - @mtorpey do you think?

However, isn't GAPDoc a required package to start GAP? If so, then this change may not be actually doing what you want @james-d-mitchell.

**Comment by james-d-mitchell** [comment]
Thanks @alex-konovalov, GAP now has a command line option —bare which allows it to start without having Gapdoc or the other required packages available, so having this option would definitely help!

**Comment by mtorpey** [comment]
GAPDoc is currently a requirement since it's used to build documentation when installing from a git or hg repo.  However, I can see that it would be good to make PackageManager loadable without GAPDoc.

I'd suggest changing GAPDoc to "suggested" along with having the "BuildDoc" methods fail a bit more gracefully if it's not loaded.

**Comment by james-d-mitchell** [comment]
I made a PR with this in mind, please take a look!

**Comment by mtorpey** [comment]
Made a few changes and merged.

I'm going to hold off on making new releases till the CI situation settles down.  But you use the master version of PackageManager anyway, right?

**Comment by james-d-mitchell** [comment]
Thanks @mtorpey, I think I can close this now, since it's resolved!
