### ISSUE TITLE
suggestion to change a test

### ISSUE THREAD

**Issue by ThomasBreuer** [gap-packages/PackageManager#70]
One of the tests in `tst/PackageManager.tst` involves a check whether GAPDoc in version `">= 999.0"` can be installed/loaded, and it is expected that such a version is not available.
However, if one has the develop version of GAPDoc installed then the version test replies that version `">= 999.0"` is available.
Perhaps the test should check for version `"= 999.0"`, this is most likely not available.

**Comment by mtorpey** [comment]
Well spotted!  I think I've resolved this now in 31245e0e and b8b19004.  Perhaps we should close this after the tests pass.
