### ISSUE TITLE
PKGMAN_DownloadURL mixes stdout and stderr

### ISSUE THREAD

**Issue by lgoettgens** [gap-packages/PackageManager#77]
When during the download of a file something gets written to stderr by the downloading program, the current implementation interleaves the two outputs, i.e. the error message appears somewhere inside the file. This leads to unexpected behavior when parsing the contents.
This is currently happening as `wget 1.21.2` prints `SSL_INIT` to stderr at the beginning of each download (cf. [wget mailing list](https://lists.gnu.org/archive/html/bug-wget/2021-09/msg00007.html)).

The easy solution would be to remove the interleaving behavior in https://github.com/gap-packages/PackageManager/blob/d628e846e77ffd81bbd59fc69d01847a1baf9fdc/gap/PackageManager.gi#L935
However, this is currently the only way to extract stderr from `Process` (cf. https://github.com/gap-system/gap/issues/4657).

**Comment by mtorpey** [comment]
Thanks for suggesting this!  It may be a good idea to un-interleave these, but I'm not sure what we would then do with the stderr output.  Perhaps writing to two different logs would be useful, but I'm not sure.  Open to suggestions! :)

**Comment by lgoe-ac** [comment]
Right now, it doesn't get written to any files at all, so your idea doesn't work that easily, as everything is handled by a `Process` instance. The easiest way, in my opinion, would be to add that feature (keep both stdout and stderr) there and then use it here. Then, interleaving would no longer be needed.
This has already been proposed in https://github.com/gap-system/gap/issues/4657

**Comment by mtorpey** [comment]
Ah, I see!  Sounds good to me – we can wait for the corresponding changes in GAP.

**Comment by mtorpey** [comment]
I believe this is captured by #104.
