### ISSUE TITLE
State in user manual how to install and load PackageManager

### ISSUE THREAD

**Issue by slel** [gap-packages/PackageManager#88]
Disclaimer: I am a very occasional GAP user,
and mostly via Sage; my request may make
little sense if more seasoned GAP users are
the target audience for the manual.

Could the PackageManager manual

- state how to install PackageManager itself,
  or state that it is always available in GAP,
  being a standard package (if that is the case);
  and if applicable, state how to check whether
  PackageManager is installed in one's GAP
- state that one needs to load `PackageManager`
  before running the commands it provides,
  for example as suggested in #87

**Comment by mtorpey** [comment]
Hi Samuel!  I think this is a great idea – one of the main goals of the package manager is to make things easier for occasional users, and so we should make this as clear as possible.

I should have some time to do this next week!

**Comment by mtorpey** [comment]
I see PR #87 addresses some of this already!

**Comment by mtorpey** [comment]
I've now made this a little clearer in 641fc55.  It only took me 2 years! :)
