### ISSUE TITLE
Tests fail in the PackageDistribution CI when trying to install `HomalgToCAS`

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/PackageManager#91]
The tests for `PackageManager` fail when run in the GAP package distribution CI (and always have). I've no idea why; perhaps @mtorpey or @ChrisJefferson have one...

Here is an [example log where it failed](https://github.com/gap-system/PackageDistro/runs/7837047831?check_suite_focus=true). It always fails like that. That is, the first failure is here (and then the rest probably mostly consequences of that first one):
```
########> Diff in /home/runner/gap/pkg/PackageManager-1.2/tst/PackageManager.tst:12
# Input is:
RemoveDirectoryRecursively(Filename(Directory(dir), "bin"));
# Expected output:
true
# But found:
Error, dirname must be a directory
```

**Comment by mtorpey** [comment]
I'm not sure about this!  I'll try and take a closer look when I can (but if anyone else has any ideas, do say! :) )

**Comment by fingolfin** [comment]
Yeah it flabbergasts me, too... 

The error message in the failed test comes from GAP's `RemoveDirectoryRecursively`.

The test file looks like this:
```
# Get curlInterface (for testing)
gap> InstallPackage("curlInterface");
true
gap> if DownloadURL = fail then
>   Unbind(DownloadURL);  # unbind dummy variable set in init.g
> fi;
gap> LoadPackage("curlInterface", false);
true

# Clean up and recompile curlInterface
gap> dir := PackageInfo("curlInterface")[1].InstallationPath;;
gap> RemoveDirectoryRecursively(Filename(Directory(dir), "bin"));  # <- ERROR here
true
```
One guess: above PackageManager was asked to install curlInterface, but as a matter of fact that latest curlInterface is already installed and compiled. Could it be that the value of `dir` in the penultimate test input line points to the "wrong" of the two otherwise identical curlInterface directories, and hence does not contain a `bin` directory?

**Comment by ChrisJefferson** [comment]
That's my guess too -- I was just trying to reproduce it exactly.

The whole "clean up and recompile" bit looks generally dodgy. What I'm not 100% sure about is why everything after this then also starts failing.

**Comment by ChrisJefferson** [comment]
I think that `[1]` normally works, because the newly installed package ends up at the start of the list -- but that isn't required, and it depends on the filenames (they are sorted).

I do wonder if we need to do that at all -- if we want to test compiling a package, we should probably just make up some fake package for that -- and at the least not do a package we need for PackageManager itself to function :)

**Comment by fingolfin** [comment]
Yeah, testing with a dedicated non-distributed test package would be better. Perhaps you'd want to use https://github.com/gap-packages/RegisterPackageTNUMDemo for this?

**Comment by fingolfin** [comment]
This got better with release 1.3, but it still fails, trying to install `HomalgToCAS`, possibly because some dependencies for that are absent. See [this log](https://github.com/gap-system/PackageDistro/runs/8081785189?check_suite_focus=true). Perhaps a different package w/o dependencies can be used for the test?

**Comment by fingolfin** [comment]
Actually I just realized that the test only fails installing `HomalgToCAS` when `PackageManager` was loaded using `LoadPackage("PackageManager" : OnlyNeeded);`, see [this newer log](https://github.com/gap-system/PackageDistro/actions/runs/3079640395/jobs/4976193744). That option `OnlyNeeded` disables loading `curlInterface`... except the PackageDistro tests in this case actually load `curlInterface` beforehand anyway, because the `PackageManager` test suite actually assumes `curlInterface` is available.

Unfortunately that means I have no clue anymore why it might succeed in one case and fail in the other. The error message is not very helpful either:
```
failed (package may still be usable)
#I  Package availability test failed
#I  Dependencies not satisfied for HomalgToCAS-2022.09-01
false
```
Presumably the log file(s) produced by `BuildPackages.sh` are somewhere, but where? Looking at those might give another clue

**Comment by fingolfin** [comment]
Alas, I was wrong, that wasn't the problem.

**Comment by fingolfin** [comment]
This discussion is a bit confusing and convoluted. I am going to open a fresh issue
