### ISSUE TITLE
Failing to compile IO

### ISSUE THREAD

**Issue by james-d-mitchell** [gap-packages/PackageManager#95]
In the CI build:

https://dev.azure.com/jdm3/jdm3/_build/results?buildId=2316&view=logs&jobId=1b943edf-0709-5509-a31e-3181856f1f1f&j=1b943edf-0709-5509-a31e-3181856f1f1f&t=db183856-51a5-5cf7-d8e5-5c0d340a8e3e

I'm getting:
~~~
#I  Installing dependency IO 4.7.2 ...
#I  Downloading archive from URL https://github.com/gap-packages/io/releases/download/v4.7.2/io-4.7.2.tar.gz ...
#I  Command wget not found
#I  Saved archive to /tmp/gaptempdirnISdKP/io-4.7.2.tar.gz.pkgman
#I  Extracting to /home/gap/.gap/pkg/io-4.7.2 ...
#I  Running compilation script on /home/gap/.gap/pkg/io-4.7.2 ...
#I  Possible error detected: see log at /tmp/gaptempdirPBKo2Q/exec-log.txt
#I  Compilation failed (package may still be usable)
#I  Package availability test failed
#I  (for IO 4.7.2)
#I  Removed directory /home/gap/.gap/pkg/io-4.7.2
~~~

There are two issues: 

1. Compilation fails, I don't know why, maybe this is an issue with the CI setup, or a known issue with `PackageManager`.
2. The message `package may still be usable` is not accurate if the message `Removed directory /home/gap/.gap/pkg/io-4.7.2` is accurate.

**Comment by fingolfin** [comment]
I've run into similar issues in the past. In particular the "Removed directory" bit is unfortunate because it makes debugging super hard.

It would be good if there was an option to disable the removal, for debugging.

and/or an option that could be used to make the installation more verbose, i.e., so that one sees what commands PackageManager tries to executed (e.g. `./configure --with-....`) and also the output of those.

**Comment by james-d-mitchell** [comment]
Thanks for the comments @fingolfin, do you have any ideas how to work around this issue? Older versions of `PackageManager` didn't have this problem, I don't think, I could always revert to using one of those, but wonder if there's another work around?

**Comment by fingolfin** [comment]
@james-d-mitchell I don't have a good answer for that... I suspect @mtorpey (or whoever did it) added the removal of the package directory that failed to install as a precaution, so broken packages don't litter the file system? But it makes debugging harder. Perhaps an alternative would be to move the failed package dir into a tmp dir (but that could also be hard to get right, e.g. moves across file system border can be a problem, etc.). 

Or perhaps an optional boolean flag that "dontRemoveDirs" that one can set when debugging such things could be added?

**Comment by mtorpey** [comment]
A `dontRemoveDirs` option sounds reasonable, but just to check: @james-d-mitchell is the IO compilation still failing in your example?

**Comment by james-d-mitchell** [comment]
Not relevant anymore thanks @mtorpey
